### ISSUE TITLE
Some fixes

### ISSUE THREAD

**Issue by vadimostanin** [icoz/habraparse#10]
Hello,
I tried your project to save my favourites, but I got some problems. 
I fixed problem, also added temp css for good looking, and changed pdf to landscape format, because article text went over left bound.
Here is patch
https://gist.github.com/vadimostanin/44bf976549454bc88fec54f7fd8d7899

Thank you for your project
Vadym

**Comment by icoz** [comment]
А pull-request не проще было сделать?
Кстати, вопрос: а не в landscape можете как-то переформатировать текст?
Надо что-то ведь в css поправить, а я там не силен. :(

**Comment by icoz** [comment]
@vadimostanin if you don't speak russian, tell me. I'll translate

**Comment by icoz** [comment]
Закрыто за давностью.
