### ISSUE TITLE
ValueError при отрицательной карме

### ISSUE THREAD

**Issue by a-knyazev** [icoz/habraparse#2]
float от отрицательного числа напрямую не работает

**Comment by icoz** [comment]
Дайте, пожалуйста, имя пользователя, на котором у вас вылетает эта ошибка. Что бы я мог отладить.

**Comment by icoz** [comment]
Не смог повторить ошибку. Если баг повторяется, пишите подробнее.
Какую ошибку выдает, какая версия питона используется, какая ОС?
