### ISSUE TITLE
Не работает с версией 3.4питона

### ISSUE THREAD

**Issue by zlatsv** [icoz/habraparse#20]
На попытку закачать как отдельные посты, так и каталог избранного, выдает что посты не найдены:
Downloading "Rapid STP"...
Saving it in "dir1/330358.pdf"
Post 330358 is deleted!

**Comment by icoz** [comment]
Про питон 3.4 могу сказать только, что я тестирую только 3.5 и 3.6. [travis-ci](https://travis-ci.org/icoz/habraparse)
Попробуйте использовать [докер-вариант](https://hub.docker.com/r/icoz/habraparse-auto/)

Про посты - да, поменялся формат страницы. Я поправил код разбора в  #51a49ef6.
