### ISSUE TITLE
Косячки

### ISSUE THREAD

**Issue by Elsopuro** [icoz/habraparse#6]
**Баг 1:**
float('-4.0') - ок 
float('–4.0') - не ок

**Баг 2:**
Traceback (most recent call last):
  File "./habraparse.py", line 258, in <module>
  File "./habraparse.py", line 253, in test_main
  File "./habraparse.py", line 190, in create_url_list
FileNotFoundError: [Errno 2] No such file or directory: 'icoz.txt'

Закоментил в test_main первую строку.

**Comment by icoz** [comment]
Спасибо поправлю.
Совет на будущее - на каждый баг заводите свой issue

**Comment by icoz** [comment]
Дайте, плиз, пример, где у пользователя отрицательная карма. 
Я хочу протестировать, но не могу найти таких пользователей.

**Comment by Elsopuro** [comment]
http://m.habrahabr.ru/users/coffin/

Отправлено с iPhone

**Comment by icoz** [comment]
У меня всё работает для этого пользователя.
