### ISSUE TITLE
Зависание скрипта

### ISSUE THREAD

**Issue by xvitaly** [icoz/habraparse#7]
Скрипт зависает вот на этой записи: http://habrahabr.ru/company/pt/blog/264763/

**Comment by icoz** [comment]
Боюсь, что это не мой баг.
Если запустить  скрипт без добавления комментариев

``` bash
./habraparse.py save_post 264763 264763_wc.pdf
```

то всё работает.
Если запустить его с комментариями, но сохранять в html, то получается файлик на 27Мб.
Похоже, что weasyprint банально не может его переварить. Либо ему надо много времени...
Проверьте эти варианты у себя.

**Comment by icoz** [comment]
Хм. Похоже, что поменяли метод выкладки комментов к статье... :(
Буду копать глубже

**Comment by xvitaly** [comment]
Да, без комментариев сохраняется нормально. Похоже действительно не может переварить такой огромный файл.

**Comment by icoz** [comment]
Реализовал выборку коментариев. Есть проблема с синхронизацией списков при их сшивке zip().

**Comment by icoz** [comment]
@xvitaly прошу протестировать.
Написал новую обработку комментариев. Если есть предложения как можно реализовать красивое оформление комментариев, то буду рад их услышать.
